import type { Metadata } from 'next';
import { GeistSans, GeistMono } from 'geist/font';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={GeistSans.className}>
    <body className="relative flex min-h-screen bg-gray-100">
      <aside className="sticky top-0 hidden md:block w-1/4 min-h-screen bg-[#f9fafb] shadow-sm md:w-[200px]">
        <Sidebar />
      </aside>

      <main className="max-w-6xl mx-auto w-full p-4">
        {children}
      </main>
      <Toaster />
    </body>
  </html>
  );
}
