import type { Metadata } from 'next';
import { GeistSans, GeistMono } from 'geist/font';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={GeistSans.className}>
      <body className='relative flex min-h-screen z-10'>
        <aside className='sticky top-0 z-40 hidden h-screen border-r md:block md:w-[200px] bg-white shadow-md'>
          <Sidebar />
        </aside>

        <main className='max-w-6xl mx-auto min-h-screen'>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
